feat: clean up maintainer scripts.

diff --git a/packages/debs/SPECS/wazuh-agent/debian/preinst b/packages/debs/SPECS/wazuh-agent/debian/preinst
--- a/packages/debs/SPECS/wazuh-agent/debian/preinst
+++ b/packages/debs/SPECS/wazuh-agent/debian/preinst
@@ -3,42 +3,30 @@
 # Wazuh, Inc 2024
 
 set -e
-export INSTALLATION_WAZUH_DIR="/opt/wazuh-agent"
 BINARY_DIR="/usr/share/wazuh-agent/bin/"
 
 # configuration variables
-WAZUH_TMP_DIR="${INSTALLATION_WAZUH_DIR}/tmp"
-
-# environment configuration
-if [ ! -d ${WAZUH_TMP_DIR} ]; then
-    mkdir -p ${WAZUH_TMP_DIR}
-else
-    rm -rf ${WAZUH_TMP_DIR}
-    mkdir -p ${WAZUH_TMP_DIR}
-fi
+UPGRADE_RESTART_FLAG="/tmp/wazuh.restart"
 
 case "$1" in
     install|upgrade)
 
         if [ "$1" = "upgrade" ]; then
 
-            if [ ! -d "$INSTALLATION_WAZUH_DIR" ]; then
-                echo "Error: Directory $INSTALLATION_WAZUH_DIR does not exist. Cannot perform upgrade" >&2
+            if [ ! -d "$BINARY_DIR" ]; then
+                echo "Error: Directory $BINARY_DIR does not exist. Cannot perform upgrade" >&2
                 exit 1
             fi
 
             if command -v systemctl > /dev/null 2>&1 && systemctl > /dev/null 2>&1 && systemctl is-active --quiet wazuh-agent > /dev/null 2>&1; then
                 systemctl stop wazuh-agent > /dev/null 2>&1
-                touch ${WAZUH_TMP_DIR}/wazuh.restart
-            elif command -v service > /dev/null 2>&1 && service wazuh-agent status 2>/dev/null | grep "is running" > /dev/null 2>&1; then
-                service wazuh-agent stop > /dev/null 2>&1
-                touch ${WAZUH_TMP_DIR}/wazuh.restart
+                touch ${UPGRADE_RESTART_FLAG}
             elif ${BINARY_DIR}wazuh-agent --status 2>/dev/null | grep "is running" > /dev/null 2>&1; then
                 pid=$(ps -ef | grep "${BINARY_DIR}wazuh-agent" | grep -v grep | awk '{print $2}')
                 if [ -n "$pid" ]; then
                     kill -SIGTERM "$pid" 2>/dev/null
                 fi
-                touch ${WAZUH_TMP_DIR}/wazuh.restart
+                touch ${UPGRADE_RESTART_FLAG}
             fi
 
         fi
